spring:
  application:
    name: payment-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8102

management:
  endpoints:
    web:
      exposure:
        include: health
