spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: gateway
    password: gateway

shared:
  security:
    merchant-service:
      base-url: http://localhost:8101

gateway:
  aws:
    region: eu-north-1
    credentials:
      access-key: test
      secret-key: test
    sns:
      endpoint: http://localhost:4566
  payment:
    token-service:
      base-url: http://localhost:8103
      internal-token: dev-secret-payment
    acquirer-service:
      base-url: http://localhost:8105
      internal-token: dev-secret-payment
    internal:
      callers:
        - id: checkout-service
          secret: dev-secret-checkout
    outbox:
      topic-arn: arn:aws:sns:eu-north-1:000000000000:payment-events
